#!/usr/bin/bash

# Use Flameshot to take a screenshot and copy it to the clipboard
flameshot gui --raw | wl-copy

# Notify the user that the screenshot has been copied
notify-send "Screenshot copied to clipboard" -a "ss"
